##1. Write a Python Program to Add Two Matrices?

In [3]:
## ANS
a = [[8,9,6],
     [4,6,9],
     [7,5,4]]

b = [[1,5,6],
     [5,9,9],
     [2,5,6]]
    
result = [[0,0,0],
          [0,0,0],
          [0,0,0]]

for i in range(len(a)):
  for j in range(len(a[0])):
    result[i][j] = a[i][j] + b[i][j]
for r in result:
  print(r)

[9, 14, 12]
[9, 15, 18]
[9, 10, 10]


##2. Write a Python Program to Multiply Two Matrices?

In [22]:
## ANS
import numpy as np
a = np.random.randint(1,10, size=(3,3))                ## it will create a 3x3 matrix with random integers between 1 to 10
print(f"Matrix a is equal to: ")
print(a)
b = np.random.randint(1,10, size=(3,3))
print(f"Matrix b is equal to: ")
print(b)
result = np.dot(a,b)                                             ## dot is a bulti-in matrix multiplication function in numpy
print("Result of matrix multiplication of a and b is: ")
print(result)

Matrix a is equal to: 
[[7 7 2]
 [9 9 7]
 [9 3 3]]
Matrix b is equal to: 
[[4 6 7]
 [7 1 7]
 [5 1 1]]
Result of matrix multiplication of a and b is: 
[[ 87  51 100]
 [134  70 133]
 [ 72  60  87]]


##3. Write a Python Program to Transpose a Matrix?

In [31]:
## ANS
import numpy as np
a = np.random.randint(1,10, size=(4,2))                 ## create matrix a of size 4x2
print("matrix a is: ")
print(a)
result = np.zeros(shape=(2,4), dtype=int)               ## create zero matrix of size 2x4 which we use to store the transpose values of a

for i in range(len(a)):
  for j in range(len(a[0])):
    result[j][i] = a[i][j]

print("Transpose of a matrix is: ")
for r in result:
  print(r)

matrix a is: 
[[4 5]
 [4 2]
 [5 5]
 [1 1]]
Transpose of a matrix is: 
[4 4 5 1]
[5 2 5 1]


##4. Write a Python Program to Sort Words in Alphabetic Order?

In [2]:
## ANS
words = input("Enter a sentence: ")
words = words.split(" ")
s = sorted(words)
print("Sentence after sorting is: ")
print(' '.join(s))

Enter a sentence: Write a Python Program to Sort Words in Alphabetic Order?
Sentence after sorting is: 
Alphabetic Order? Program Python Sort Words Write a in to


##5. Write a Python Program to Remove Punctuation From a String?

In [7]:
## ANS
string = input("Enter a string: ")
print(f"The original string is : {string} " )

punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''            # initializing punctuations string

for i in string:
	if i in punc:
		string = string.replace(i, "")
  
print(f"The string after punctuation filter : {string}")


Enter a string: ineuron full stack$%^& data%^&* science$%^& bootcamp>:{
The original string is : ineuron full stack$%^& data%^&* science$%^& bootcamp>:{ 
The string after punctuation filter : ineuron full stack data science bootcamp
